name: Upload APK to Play Store

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node dependencies
        run: npm ci

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-release-key.keystore

      - name: Decode Fastlane JSON
        run: echo "${{ secrets.SUPPLY_JSON_KEY }}" | base64 -d > android/fastlane/playstore.json

      - name: Grant Permission to Gradlew
        run: chmod +x ./android/gradlew

      - name: Build AAB
        run: |
          cd android
          ./gradlew bundleRelease \
            -PMYAPP_UPLOAD_STORE_FILE=my-release-key.keystore \
            -PMYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
            -PMYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }} \
            -PMYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

      - name: Deploy with Fastlane
        run: |
          cd android
          bundle install
          bundle exec fastlane internal
